//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServiceReferenceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocios")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CapaPresentacion.ServiceReferenceUsuario.Usuario[] UsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CapaPresentacion.ServiceReferenceUsuario.Usuario[] Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esExitoso {
            get {
                return this.esExitosoField;
            }
            set {
                if ((this.esExitosoField.Equals(value) != true)) {
                    this.esExitosoField = value;
                    this.RaisePropertyChanged("esExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CapaDatos")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuario.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/AgregarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/AgregarUsuarioResponse")]
        CapaPresentacion.ServiceReferenceUsuario.Respuesta AgregarUsuario(string nombre, System.Nullable<System.DateTime> fecha, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/AgregarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> AgregarUsuarioAsync(string nombre, System.Nullable<System.DateTime> fecha, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ModificarUsuarioResponse")]
        CapaPresentacion.ServiceReferenceUsuario.Respuesta ModificarUsuario(string nombre, System.Nullable<System.DateTime> fecha, string sexo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> ModificarUsuarioAsync(string nombre, System.Nullable<System.DateTime> fecha, string sexo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ConsultarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarUsuariosResponse")]
        CapaPresentacion.ServiceReferenceUsuario.Respuesta ConsultarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ConsultarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarUsuariosResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> ConsultarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EliminarUsuarioResponse")]
        CapaPresentacion.ServiceReferenceUsuario.Respuesta EliminarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> EliminarUsuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : CapaPresentacion.ServiceReferenceUsuario.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<CapaPresentacion.ServiceReferenceUsuario.IUsuarioService>, CapaPresentacion.ServiceReferenceUsuario.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaPresentacion.ServiceReferenceUsuario.Respuesta AgregarUsuario(string nombre, System.Nullable<System.DateTime> fecha, string sexo) {
            return base.Channel.AgregarUsuario(nombre, fecha, sexo);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> AgregarUsuarioAsync(string nombre, System.Nullable<System.DateTime> fecha, string sexo) {
            return base.Channel.AgregarUsuarioAsync(nombre, fecha, sexo);
        }
        
        public CapaPresentacion.ServiceReferenceUsuario.Respuesta ModificarUsuario(string nombre, System.Nullable<System.DateTime> fecha, string sexo, int id) {
            return base.Channel.ModificarUsuario(nombre, fecha, sexo, id);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> ModificarUsuarioAsync(string nombre, System.Nullable<System.DateTime> fecha, string sexo, int id) {
            return base.Channel.ModificarUsuarioAsync(nombre, fecha, sexo, id);
        }
        
        public CapaPresentacion.ServiceReferenceUsuario.Respuesta ConsultarUsuarios() {
            return base.Channel.ConsultarUsuarios();
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> ConsultarUsuariosAsync() {
            return base.Channel.ConsultarUsuariosAsync();
        }
        
        public CapaPresentacion.ServiceReferenceUsuario.Respuesta EliminarUsuario(int idUsuario) {
            return base.Channel.EliminarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceUsuario.Respuesta> EliminarUsuarioAsync(int idUsuario) {
            return base.Channel.EliminarUsuarioAsync(idUsuario);
        }
    }
}
